### ISSUE TITLE
Nil Pointer error when running on Windows 7

### ISSUE THREAD

**Issue by perfectmak** [FleekHQ/space-daemon#90]
### Expected Behaviour ###
The daemon should run and get started successfully.

### Actual Behaviour ###
The daemon fails with a nil pointer reference error during startup

### Extra information ###
Daemon Version: space_Windows_x86_64.exe v0.0.9
Operating System: Windows 7

Logs
```
time="2020-07-13T14:10:29+01:00" level=debug msg="Running mode" DevMode=false
time="2020-07-13T14:10:29+01:00" level=debug msg="Running daemon with profiler.
Visit http://localhost:6060/debug/pprof"
2020/07/13 14:10:29 Error loading .env file. Using defaults
time="2020-07-13T14:10:29+01:00" level=info msg="using path ~/.fleek-space for s
tore"
badger 2020/07/13 14:10:29 INFO: All 1 tables opened in 3ms
badger 2020/07/13 14:10:29 INFO: Replaying file id: 0 at offset: 385
badger 2020/07/13 14:10:29 INFO: Replay took: 36.002ms
badger 2020/07/13 14:10:29 DEBUG: Value log discard stats empty
time="2020-07-13T14:10:29+01:00" level=debug msg="Starting Component" name=Store
 
time="2020-07-13T14:10:29+01:00" level=debug msg="Starting Component" name=Folde
rWatcher
time="2020-07-13T14:10:36+01:00" level=info msg="Welcome to bucket" peerID=12D3K
ooWM3RXmueyLKYfevsVi4zP5q27QLe5zR3UEkmcEthcyDxp
time="2020-07-13T14:10:36+01:00" level=debug msg="Starting Component" name=Bucke
tDaemon
time="2020-07-13T14:10:36+01:00" level=debug msg="Starting Async Component" name
=TextileClient
time="2020-07-13T14:10:36+01:00" level=debug msg="Generating key pair..."
time="2020-07-13T14:10:36+01:00" level=debug msg="Error generating key pair, key
 might already exist"
time="2020-07-13T14:10:36+01:00" level=debug msg="Error while executing Generate
KeyPair. Key pair already exists. Use GenerateKeyPairWithForce if you want to ov
erride it."
time="2020-07-13T14:10:36+01:00" level=debug msg="Starting Textile Client..."
time="2020-07-13T14:10:36+01:00" level=debug msg="Creating buckets client in 127
.0.0.1:3006"
time="2020-07-13T14:10:36+01:00" level=debug msg="Creating threads client in 127
.0.0.1:3006"
time="2020-07-13T14:10:36+01:00" level=debug msg="Creating default bucket..."
time="2020-07-13T14:10:36+01:00" level=debug msg="Creating a new bucket with slu
g personal"
time="2020-07-13T14:10:36+01:00" level=debug msg="Fetching thread id from local
store"
time="2020-07-13T14:10:36+01:00" level=debug msg="No persisted mountFuseDrive st
ate found"
time="2020-07-13T14:10:36+01:00" level=debug msg="Starting Component" name=FuseC
ontroller
time="2020-07-13T14:10:36+01:00" level=debug msg="Starting Async Component" name
=BucketSync
time="2020-07-13T14:10:36+01:00" level=debug msg="Fetching thread id from local
store"
time="2020-07-13T14:10:36+01:00" level=debug msg="Thread ID found in local store
"
time="2020-07-13T14:10:36+01:00" level=debug msg="Thread ID found in local store
"
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0xf8dbc6]
 
goroutine 2123 [running]:
github.com/textileio/go-threads/db.(*DB).GetCollection(0x0, 0xc00a8ac647, 0x7, 0
x0, 0x0, 0x0, 0x0)
        /Users/runner/go/pkg/mod/github.com/textileio/go-threads@v0.1.21/db/db.g
o:355 +0x46
github.com/textileio/go-threads/api.(*Service).getCollection(0xc00008e338, 0x21a
3740, 0xc00a899e60, 0xc00a8ac647, 0x7, 0xc00a6cf1a0, 0x22, 0x0, 0x0, 0x409f32, .
..)
        /Users/runner/go/pkg/mod/github.com/textileio/go-threads@v0.1.21/api/ser
vice.go:856 +0xd0
github.com/textileio/go-threads/api.(*Service).Find(0xc00008e338, 0x21a3740, 0xc
00a899e60, 0xc00a8ee480, 0xc00008e338, 0x0, 0x0)
        /Users/runner/go/pkg/mod/github.com/textileio/go-threads@v0.1.21/api/ser
vice.go:460 +0x226
github.com/textileio/go-threads/api/pb._API_Find_Handler.func1(0x21a3740, 0xc00a
899e60, 0x18c1b20, 0xc00a8ee480, 0x0, 0x0, 0x0, 0xc00a8ee480)
        /Users/runner/go/pkg/mod/github.com/textileio/go-threads@v0.1.21/api/pb/
threads.pb.go:3170 +0x8d
github.com/grpc-ecosystem/go-grpc-middleware/auth.UnaryServerInterceptor.func1(0
x21a3740, 0xc00a899e30, 0x18c1b20, 0xc00a8ee480, 0xc00a897a60, 0xc00a897a80, 0xf
f21e1, 0x1842e40, 0xc00a897aa0, 0xc00a897a60)
        /Users/runner/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1
.2.0/auth/auth.go:47 +0x10f
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1(0x21a374
0, 0xc00a899e30, 0x18c1b20, 0xc00a8ee480, 0xc00a36fc00, 0x0, 0xc00a627b30, 0x40d
c2f)
        /Users/runner/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1
.2.0/chain.go:25 +0x6a
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1(0x21a3740, 0
xc00a899e30, 0x18c1b20, 0xc00a8ee480, 0xc00a897a60, 0xc00a897a80, 0xc00a627ba0,
0x4aa0ef, 0x1887d80, 0xc00a899e30)
        /Users/runner/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1
.2.0/chain.go:34 +0xdc
github.com/textileio/go-threads/api/pb._API_Find_Handler(0x196e300, 0xc00008e338
, 0x21a3740, 0xc00a899e30, 0xc00a8ee420, 0xc0076a7ad0, 0x21a3740, 0xc00a899e30,
0xc00aa94200, 0x77)
        /Users/runner/go/pkg/mod/github.com/textileio/go-threads@v0.1.21/api/pb/
threads.pb.go:3172 +0x152
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0003ab6c0, 0x21b9b60, 0xc005
bcfe00, 0xc00a36fc00, 0xc0004be450, 0x2f72518, 0x0, 0x0, 0x0)
        /Users/runner/go/pkg/mod/google.golang.org/grpc@v1.30.0/server.go:1171 +
0x511
google.golang.org/grpc.(*Server).handleStream(0xc0003ab6c0, 0x21b9b60, 0xc005bcf
e00, 0xc00a36fc00, 0x0)
        /Users/runner/go/pkg/mod/google.golang.org/grpc@v1.30.0/server.go:1494 +
0xcd4
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc00729b7f0, 0xc0003ab6c0
, 0x21b9b60, 0xc005bcfe00, 0xc00a36fc00)
        /Users/runner/go/pkg/mod/google.golang.org/grpc@v1.30.0/server.go:834 +0
xa8
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /Users/runner/go/pkg/mod/google.golang.org/grpc@v1.30.0/server.go:832 +0
x20b
```

**Comment by Djeremaille** [comment]
Same error on Ubuntu 18.04.

**Comment by jsonsivar** [comment]
Bumping this.  There have been a lot of changes since this issue was opened and doesn't appear to be happening atm.  Cool if we close this?
